query(
    $user_recebe:Int!
    $count:Int!
    $page:Int!
){
  mensagemUserRecebe(user_recebe:$user_recebe,count:$count,page:$page,orderBy:[{field:"id",order:DESC}]){
    data{
      id
      mensagem
      date
      proposta_categoria{
        id
        descricao
        titulo
        valor
        local
        tempo
        tipo
        status
        date
        user_envia{
          imagem
          user{
            name
          }
        }
      }
      user_envia{
        id
        imagem
        user{
          name
        }
      }
      user_recebe{
        imagem
        user{
          name
        }
      }
      resposta{
        id
        reply
        date
        user_envia{
          imagem
          user{
            name
          }
        }
        mensagem{
          id
          user_envia{
            user{
              name
            }
          }
        }
      }
    }
    paginatorInfo{
      count
      currentPage
      firstItem
      hasMorePages
      lastItem
      perPage
      lastPage
      total
    }
  }
}