query
    (
        $user_envia:Int!
        $count:Int!
        $page:Int!
    )
{
  mensagemUserEnvia(user_envia:$user_envia,count:$count,page:$page,orderBy:[{field:"id",order:DESC}]){
    data{
      id
      mensagem
      date
      user_envia{
        id
        imagem
        user{
          name
        }
      }
      user_recebe{
        imagem
        user{
          name
        }
      }
    	proposta_categoria{
        id
        titulo
        valor
      }
      resposta{
        id
        reply
        date
        user_envia{
          id
          imagem
          user{
            name
          }
        }
        mensagem{
          id
          user_envia{
            user{
              name
            }
          }
          user_recebe{
            user{
              name
            }
          }
        }
      }
    }
    paginatorInfo{
      count
      currentPage
      firstItem
      hasMorePages
      lastItem
      perPage
      lastPage
      total
    }
  }
}