query($id: Int!){
  imageForUserId(user_id:$id){
    id
    imagem
    ramo
  	cidade
  	estado
  	descricao
    telefone
  	logradouro
  	user{
      id
      name
    }
  	category{
      id
      name
    }
  }
}