query(
  $user_envia_id:Int!
  $count:Int!
  $page:Int!
){
  propostaEnvia(user_envia_id:$user_envia_id,count:$count,page:$page,orderBy:[{field:"id",order:DESC}]){
    data{
      id 
      titulo
      valor
      local
      descricao
      tipo
      status
      date
      tempo
      finalizar
      user_envia{
        id
        user{
          id
          name
        }
        cidade
        estado
        imagem
        telefone
        logradouro
      }
      user_recebe{
        id
        user{
          id
          name
          email
        }
        imagem
        ramo
        descricao
        cidade
        estado
        telefone
        logradouro
        category{
          name
        }
      }
      orcamento{
        id
        data
        horaInicio
        horaFim
        descricao
        proposta{
          id
        }
      }
    }
    paginatorInfo{
      count
      currentPage
      firstItem
      hasMorePages
      lastItem
      lastPage
      perPage
      total
    }
  }
}

# query($user_envia_id: Int!){
#   propostaEnvia(user_envia_id:$user_envia_id){
#     id 
#     titulo
#     valor
#     local
#     descricao
#     tipo
#     status
#     date
#     tempo
#     finalizar
#     user_envia{
#       id
#       user{
#         id
#         name
#       }
#       cidade
#       estado
#       imagem
#       telefone
#       logradouro
#     }
#     user_recebe{
#       id
#       user{
#         id
#         name
#         email
#       }
#       imagem
#       ramo
#       descricao
#       cidade
#       estado
#       telefone
#       logradouro
#       category{
#         name
#       }
#     }
#     orcamento{
#       id
#       data
#       horaInicio
#       horaFim
#       descricao
#       proposta{
#         id
#       }
#     }
#   }
# }
