query
( 
    $category: Int!
){
  propostaForCatLimit(category:$category){
  	id
    titulo
    valor
    local
    descricao
    tipo
    tempo
    date
    status
    user_envia{
      id
      cidade
      estado
      imagem
      telefone
      logradouro
      user{
        id
        name
        email
      }
    }
    user_aceito{
     id
      cidade
      estado
      imagem
      telefone
      logradouro
      user{
        id
        name
        email
      }
    }
    category{
      name
    }
    lances{
      id
      data
      horaInicio
      horaFim
      descricao
      user_lance{
        id
        user{
          name
        }
      }
    }  
  }
}