query
(
  $user_envia:Int!
  $count:Int!
  $page:Int!
)
{
  propostaEnviaCat(
    user_envia:$user_envia,count:$count,page:$page,orderBy:[{field:"id",order:DESC}]
  ){
    data{
      id
      titulo
      valor
      local
      descricao
      tipo
      date
      tempo
      status
      lances{
        id
        data
        horaInicio
        horaFim
        status
        descricao
        user_lance{
          user{
            name
            email
          }
        }
      }
      user_envia{
        cidade
        estado
        imagem
        telefone
        logradouro
        user{
          name
        }
      }
      user_aceito{
        id
        imagem
        ramo
        descricao
        cidade
        estado
        telefone
        logradouro
        category{
          name
        }
        user{
          id
          name
          email
        }
      }
      category{
        name
        image
      }
    }
    paginatorInfo{
      count
      currentPage
      firstItem
      hasMorePages
      lastItem
      lastPage
      perPage
      total
    }
  }
}