
query
($user_recebe_id:Int!,$count:Int!,$page:Int!){
  propostaRecebe(user_recebe_id:$user_recebe_id,count:$count,page:$page,orderBy:[{field:"id",order:DESC}]){
    data{
    	id 
      titulo
      valor
      local
      descricao
      tipo
      status
      tempo
      date
      finalizar
      user_envia{
        id
        user{
          id
          name
          email
        }
        cidade
        estado
        imagem
        telefone
        logradouro
      }
      user_recebe{
        id
        user{
          id
          name
          email
        }
        imagem
        ramo
        descricao
        cidade
        estado
        telefone
        logradouro
        category{
          name
        }
      }
      orcamento{
        id
        data
        horaInicio
        horaFim
        descricao
        proposta{
          id
        }
      }  
    }
    paginatorInfo{
      count
      currentPage
      firstItem
      hasMorePages
      lastItem
      lastPage
      perPage
      total
    }
  }
}